let data = {};

data.commonFirstNames = ["Alexander", "Amanda", "Sunny-Dee", "Andrew", "Angela", "Anna", "Anthony", "Ashley", "Barbara", "Benjamin", "Betty", "Brandon", "Brenda", "Brian", "Carol", "Carolyn", "Catherine", "Charles", "Christine", "Christopher", "Cynthia", "Daniel", "David", "Deborah", "Debra", "Dennis", "Donald", "Donna", "Dorothy", "Edward", "Elizabeth", "Emily", "Emma", "Eric", "Frank", "Gary", "George", "Gregory", "Helen", "Jack", "Jacob", "James", "Janet", "Jason", "Jeffrey", "Jennifer", "Jerry", "Jessica", "John", "Jonathan", "Joseph", "Joshua", "Justin", "Karen", "Katherine", "Kathleen", "Kenneth", "Kevin", "Kimberly", "Larry", "Laura", "Linda", "Lisa", "Margaret", "Maria", "Mark", "Mary", "Matthew", "Melissa", "Michael", "Michelle", "Nancy", "Nicholas", "Nicole", "Pamela", "Patricia", "Patrick", "Paul", "Rachel", "Raymond", "Rebecca", "Richard", "Robert", "Ronald", "Ruth", "Ryan", "Samantha", "Samuel", "Sandra", "Sarah", "Scott", "Sharon", "Shirley", "Stephanie", "Stephen", "Steven", "Susan", "Thomas", "Timothy", "William", "Buddy", "Rocky", "Tanya", "Rhoderick"];
data.commonLastNames = ["Rugs", "Suitweasel", "Alvarez", "Facsimile", "Proxy", "Hayfever", "Bennet", "Brooks", "Suitcases", "Lootman", "Binman", "Castillo", "Chavez", "Cough", "Piledriver", "Crutches", "Forehead-Greives", "Braeburn", "Chassis", "Lips", "Heisenburg", "Porcelain", "Italics", "Flores", "New-Roman", "Garcia", "Gomez", "Gonzales", "Gray", "Green", "Gutierrez", "Hall", "Harris", "Hernandez", "Hill", "Howard", "Hughes", "Jackson", "James", "Jimenez", "Johnson", "Jones", "Kelly", "Kim", "King", "Lee", "Lewis", "Long", "Lopez", "Martin", "Martinez", "Mendoza", "Miller", "Mitchell", "Moore", "Morales", "Morgan", "Morris", "Murphy", "Myers", "Nelson", "Nguyen", "Ortiz", "Parker", "Patel", "Perez", "Peterson", "Phillips", "Price", "Ramirez", "Ramos", "Reed", "Reyes", "Richardson", "Rivera", "Roberts", "Robinson", "Rodriguez", "Rogers", "Kingdom", "Ruiz", "Sanchez", "Sanders", "Horcrux", "Smith", "Stewart", "Taylor", "Thomas", "Thompson", "Torres", "Turner", "Traction", "Embellishment", "Watson", "White", "Williams", "Wilson", "Wood", "Bear"];
data.uncommonFirstNames = ["Achilles", "Ahma", "Aisha", "Understanding", "Almas", "Andrea", "Angela", "Annabelle", "Avi", "Axel", "Ayham", "Azza", "Slots", "Bishop", "Bishti", "Brantley", "Chloe", "Colson", "Cristiano", "Davian", "Client", "Delta", "Coarse", "Dharv", "Easton", "Edith", "Eleanor", "Elliot", "Elsa", "Emmett", "Faith", "Mordor", "Foster", "Freja", "Friederike", "Gatlin", "Gav", "Genesis", "Glenda", "Gorakh", "Greta", "Hana", "Helena", "Hitomi", "Houria", "Ichiro", "Ingrid", "Jacqueline", "Jemimah", "Jolololo", "Judson", "Kadek", "Kai", "King", "Kobe", "Koji", "Koko", "Kylen", "Lathan", "Ledger", "Leif", "Lestat", "Luqman", "Lyle", "Malaika", "Marcel", "Marina", "Maverick", "Mavis", "Twilight", "Namya", "Niall", "Nidal", "Nikita", "Nova", "Obodas", "Penny", "Pradeep", "Priscilla", "Rafael", "Rayne", "Oust", "Sakura", "Sammie", "Shanice", "Shepherd", "Shirley", "Silas", "Siobhan", "Teka", "Tetsu", "Trish", "Tristian", "Troy", "Vince", "Wael", "Wesley", "Yolanda", "Zane", "Zayd", "Chance", "Ciel", "Forrest", "Abimbola", "Sadio", "Clandestine", "Bashful", "Seymour", "Enormous", "Constant", "Dr.", "Mrs.", "Galactic Space Explorer", "Certain Misfortune", "Sir. Three Eyes", "Pending Investigation", "Crazy Horse", "Obnoxious", "Cornelius", "Wolf", "Sheep", "Strange", "Xander", "Halo", "Arson", "Detective", "Hairy", "Bigbite", "Lump", "Listen Linda", "Jagger", "Splash", "Mojo", "Pitter Patter", "Salmonella", "Chunky", "Phlegm", "Body", "Terrential", "Astounded", "Plum", "Unreal", "Acting", "Sentimental", "Krang", "Boudica", "Guitar", "Creaky", "Tiny", "Melodic", "Deep", "Darth", "Lucifer", "Nil", "Any", "Hyper", "KVIIIlyn", "Adalbert", "Cosmo", "Vitalik", "Tree", "One", "Baby", "Hammer", "Plunger", "Coaster", "Fingers", "Pleasing", "Slippery", "Spiny", "Magic", "Sunshine", "Nope", "Majestic", "Spikey", "Toothy", "Shark", "Mundane", "Pretty", "Snow", "Banjo", "Drummer", "Double", "Peregrine", "Bobby", "Silly", "Rodd"];
data.uncommonLastNames = ["Acharya", "Agnor", "Alvin", "Anouilh", "Auclair", "Awolowo", "Bain", "Bajwa", "Bardot", "Barrere", "Bassett", "Beauregard", "Beckon", "Bellamy", "Bhatt", "Blaine", "Bockham", "Bonds", "Brassard", "Braun", "Brierman", "Caparasso", "Cellier", "Channing", "Cienfuegos", "Coachman", "Dardar", "De", "Ezekwesili", "Fēngē", "Fisk", "Flammia", "Floquet", "Fontana", "Fonua", "Freed", "Fukushima", "Furyk", "Garg", "Gaumond", "Gifford", "Ginsberg", "Guǎngchǎng", "Hamilcar", "Hanlon", "Hatterfield", "Hinode", "Houde", "Hoyabembe", "Hubert", "Humphrey", "Ironsi", "Jacaranda", "Jessup", "Johnstone", "Joubert", "Kobayashi", "Kuàng", "Lafitte", "Lù", "Machal", "Mangiarotti", "Maroney", "McCulloch", "McGowan", "McGregor", "McKenzie", "McKneese", "Mikan", "Momo", "Nabopolassar", "Najafzadeh", "O'Callaghan", "Dodecahedron", "Ogreson", "Oyatsu", "Ozanne", "Palomer", "Paquet", "Pedigrue", "Prevost", "Puabi", "Sanders", "Sargon", "Shinobi", "Shukla", "Sketchkov", "Smithsonian", "Victory", "Swedge", "Tasse", "Tokei", "Trout", "Tsukumo", "van der Beek", "Varville", "Caprisun", "Yates", "Yeshua", "Zhǒng", "Li", "Abdullah", "Log", "Frown", "Colon", "Huffer", "Cocque", "Buttz", "Crackle", "Buzzing", "Pounder", "Winter", "Pluto", "XII", "The Great", "The Not So Great", "The Small", "The Big", "Junior", "Senior", "Binjuice", "Zapper", "Envy", "Alphabet", "Capone", "Sweeper", "Towel", "Mouthful", "Walker", "Sprinter", "Mystique", "Phantom", "Synopsis", "Portfolio", "Snot", "Trickle", "Fountain", "Skidmark", "Armistice", "Drawbridge", "Alluminium", "Glazing", "Taint", "Jaws", "Glovebox", "Manhattan", "String", "Wellington", "Banana", "Unit", "Exotic", "Slayer", "Morningstar", "Antimatter", "Quantum", "Supernova", "Soap", "Ladder", "Colander", "Spoon", "Hugger", "One", "Baby", "Coaster", "Clock", "Brush", "Bucket", "Umbrella", "Whippersnapper", "Lollygag", "Egg", "Hellbender", "Wobbegong", "Panda", "Potato", "Flap", "Squirrel", "Armadillo", "Wizard", "Octopus", "Luggage", "Dragon", "Demon", "Trumpet", "Panhandle", "Bass", "Bagpipes", "Firebird", "Autocue", "Axelrod", "Tuna", "Black", "Insurance", "Moreplease", "Newcarsmell"];
data.weirdNames = ["Aristotle", "Armpit", "Backsplash", "Dastardly", "Beaverclown", "Beef", "Berry", "Biggums", "Blade", "Bloviate", "Brick", "Lemonparty", "Cemetery", "Chief", "Chilly", "Chipper", "Cilantro", "Cleopatra", "Collywobbles", "Colon", "Constantinople", "Conundrum", "Corncake", "Cowardly", "Crabwalk", "Crayola", "Creepy", "Cruel", "Dewlap", "Disco", "Dumfoozle", "Featherskin", "Fingers", "Fishery", "Flinch", "Fury", "Gardyloo", "Glasshouse", "Handsome", "Helvetica", "Hero", "Hideous", "Kitten", "Lasagna", "Le Stonks", "Legend", "Leghair", "Love", "Magic", "Markcosmisplats", "Market", "Marmaduke", "Marmalade", "Mercutio", "Moon", "Mountainous", "Nincompoop", "Noddy", "O'Yacklebrunt", "Outstanding", "Oysterbury", "Periscope", "Philtrum", "Pigpen", "Piles", "Prunella", "Rastafloods", "Ribeye", "Scrawnie", "Shivers", "Shrimpgun", "Sialoquent", "Silverback", "Sir", "Skyscraper", "Snuggles", "So-sure", "Sod", "Spike", "Stumble", "Sweet Tea", "Teeth", "Tidy", "Tiger", "Tweetly", "Van Clamberwobble", "Van Winkle", "Vanilla", "Wabbit", "Whatnot", "Widdershins", "Wigglebottom", "Woodstaff", "Zeus", "Zoro", "Plug", "gm", "Ovenmits", "Rugpull", "Tissue", "Moonshot", "ABC", "Number 27 Bus", "Noun", "Pidgeon", "Giant Mushroom", "Huge Whale", "wagmi", "Metaverse", "Timepiece", "Toenail", "Extractor Fan", "Tell-all", "Santa", "Triceratops", "Shoelace", "Alien", "Windings", "Pop-Three", "Ajax", "Exclaim", "Refund", "ABCDE", "808", "Kal-El", "Absolute Zero", "DNA", "Fax", "Super", "Genius", "Bigly", "888", "Revenue", "Hullaballoo", "Bumbershoot", "Cattywampus", "Noob", "Gardyloo", "Slumgullion", "LOL", "Aye-aye", "Boops Boops", "Thundergoose", "Von Gimmefood", "The GOAT", "Bazooka", "Pet", "Rock", "Boomer"];
data.uniqueNames = ["Lazy Lions", "Cryptodads", "Knights of Degen", "SoRare", "8 Bit Sports", "Footium", "Fives", "NFTeams", "Aifa", "Metasoccer", "NFT FC", "Krause House", "League DAO", "Ballerz", "All Star Freaks", "Big Head Soccer Club", "NFTUT", "Rookies", "Will Barrow", "Neil Down", "Danny Dan-Dandy", "Flick Balls", "Anil Probes", "Bon Jontovi", "Shania Grain", "Bunny Bundtcake", "Inspector Ratchet", "Paula Logan", "Indigo Foreverago", "Crackle Poppins", "Mary Kate", "Babe Truth", "Sue Ndamukong", "Wally World", "Rustie Wingnut", "Crescent Moon", "Lily Liliac", "Constance Sufferman", "Vincent Van No", "Cobbed Corn", "Hugh Jackedman", "Ty Slob", "Kat Inmouse", "Kid Rockins", "Entire Pizza", "Glorious Esteban", "Leroy Jenkins", "Gray Matter", "Anita Hit", "Miranda Wright", "Goodwill Hunting"];

data.personalities = ["Placid", "Appreciative", "Compassionate", "Confident", "Focused", "Humorous", "Idealistic", "Innovative", "Modest", "Passionate", "Romantic", "Sage", "Stoic", "Wise", "Indecisive", "Hot-headed", "Exhausting", "Insecure", "Bold", "Argumentative", "Dreamer", "Optimistic", "Deluded", "Stubborn", "Easy-going", "Electric"];

data.playerClasses = ["General", "Support", "Hype", "Consistency", "Investigator", "Closer", "Specialist"];
data.fanClasses = ["Die-hard", "Fair-weather", "There for the booze", "Hardcore", "Barstool", "Lunatic", "Pessimist", "Gambler", "Corporate guest", "Optimist", "Scarf Guy"];
data.staffClasses = ["Groundskeeper", "Cook", "Kit Manager", "Zookeeper", "Physio", "Sport Psychologist", "Strength Coach", "Security guard", "Social media intern", "Media team", "Equipment Handler", "Masseuse", "Yoga instructor", "Contract negotiater", "Scout", "TV Analyst", "Brand Manager", "Intern", "Marketing Manager", "Middle Manager", "Data Analyst", "Doctor", "Sponsorship Manager", "Hype person", "Waterperson", "Player Agent", "Mycologist", "Mascot", "Journalist"];
data.managementClasses = ["Assistant Coach", "Director", "Head Coach", "GM", "Owner"];

data.phobias = ["Affairs", "Aging", "Alarm clocks", "Algorithms", "Ambulances", "Anime", "Arcades", "Astrology", "Bad Vibes", "Balconies", "Bar Fights", "Barbers", "Basements", "Basilisks", "Beer", "Birds", "Black Sand", "Blankets", "Blenders", "Blue", "Boogers", "Breakfast", "Bricks", "Bright Lights", "Broomsticks", "Buffets", "Burps", "Buttons", "Calculus", "Calories", "Candles", "Carbohydrates", "Cat Hair", "Caviar", "Chains", "Champagne", "Cheese", "Cherries", "Clowns", "Coffee Beans", "Commitment", "Computer Viruses", "Concerts", "Contortionists", "Cracks", "Credit cards", "Crows", "Crying", "Curry", "Cutlery", "Denmark", "Dictionaries", "Diet Soda", "Dinosaurs", "Dogs", "Door Stops", "Duct Tape", "Dust", "Ears", "Earthquakes", "EDM", "Eggs", "Electrocution", "Elves", "Email", "Exotic Dancers", "Eyelids", "Fast food", "Feet", "Fights", "Fish", "Flares", "Flying", "Fog", "Forks", "Gin", "Glass", "Goats", "Grass", "Gravel", "Groundhogs", "Guitar Strings", "Hate mail", "Heights", "Highways", "Homeopathy", "Horses", "Hot chocolate", "Hot Dogs", "Hot Tubs", "Hotel Soaps", "Hypnosis", "Improv Comedy", "Insomnia", "Irony", "Jeans", "Kangaroos", "Keyboards", "Kilts", "Lava Lamps", "Lids", "Loud music", "Love", "Macaques", "Magnetism", "Magpies", "Mannequins", "Manual Transmissions", "Marching Bands", "McDonald's", "Mercury in Retrograde", "Meteor Showers", "Midnight", "Milk", "Mirrors", "Modems", "Mouse Traps", "Moustaches", "Music", "Mythical Creatures", "Nail Salons", "Neighbors", "New York", "News", "NFTs", "Numbers", "Office Environments", "Olive Oil", "Oranges", "Paper", "Parasites", "Passwords", "Pasta", "People over 6ft", "Petrol", "Pianos", "Pigeons", "Pillow Talk", "Pimples", "Pineapples", "Pizza ovens", "Plants", "Plastic", "Plates", "Post-it Notes", "Prime Numbers", "Programmers", "Protein Powder", "Public Bathrooms", "Radiohead", "Rain", "Raincoats", "Reading", "Relatives", "Riptides", "Rugs", "Salt", "Sandals", "Santa Claus", "Scaffolding", "Scissors", "Scooters", "Screeching", "Self-driving Vehicles", "Shoe laces", "Short Fingernails", "Showers", "SIlence", "Sitcoms", "Sleep", "Slippers", "Snakes", "Sneezes", "Snow", "Soap", "Socks", "Sour Candy", "Spatulas", "Sporks", "Sprinting", "Squat racks", "Statuary", "Stingrays", "Styrofoam", "Submarines", "Subtitles", "Success", "Sunflower Seeds", "Sunglasses", "Supermarkets", "Swimming", "T-shirts", "Taxes", "Tennis Elbow", "The 80s", "The Eagles", "The Internet", "The Letter 'S'", "The Moon", "The Number 9", "Theme Parks", "Toilet Paper", "Tomato Juice", "Toothbrushes", "Touch", "Trains", "Travel", "Truck Drivers", "Twins", "Typos", "Vanilla extract", "Vegans", "VHS tapes", "Video Games", "Vikings", "Vodka", "VR Technology", "Warm Weather", "Water Pistol", "Wigs", "Windows", "Witchcraft", "Wood"];
data.vices = ["1AM", "3rd Base", "4 Syllable Words", "90s Rock", "Air Conditioning", "AM Radio", "Amsterdam", "Antibiotics", "Ants", "Argon", "Attics", "Bad Speling", "Balloons", "Bangs", "Barbecue Sauce", "Beanbags", "Beards", "Beat Poetry", "Bees", "Billboards", "Bio-diesel", "Birth", "Boardgames", "Body Spray", "Books", "Bracelets", "Brazil", "Bread Knife", "Breakfast", "Buffets", "Burritos", "Buses", "Buttered Toast", "Butterflies", "Caffeine", "Candles", "Carpets", "Cars", "Cat Food", "Catapults", "Chain Smoking", "Charities", "Cheerleaders", "Cheese", "Cheeseburgers", "Chips", "Church", "Cigars", "Clapping", "Cleaning", "Clocks", "Clouds", "Cognac", "Commercialism", "Confetti", "Conmen", "Construction", "Coral Reefs", "Craft Beer", "Custom Vans", "Cute Animals", "Dark Chocolate", "Darts", "Dentists", "Diet Soda", "Disneyland", "Dracula", "Dreams", "Dumbbells", "Dust", "Eclipses", "Elevators", "Emojis", "England", "Exobiology", "Exorcisms", "Extended laughing", "Facepaint", "Fairies", "Fan Mail", "Feet", "Fire", "Flies", "Flying", "Folk Dance", "Freeeeedom", "Frost", "Frowns", "Fungi", "Fungible Tokens", "Gates", "Geese", "Glasses", "Gossip", "Graffiti", "Grandfather", "Grannies", "Gravel", "Greeting Cards", "Gym", "Hair Bands", "Haircuts", "Halloween", "Handwriting", "Hawaiian Pizza", "Holiday Smells", "Hope", "Horse Racing", "Hot chips", "Huffing", "Influencers", "Iron Gates", "Jean shorts", "Jewelry", "Jokers", "Kangaroos", "Kittens", "Lanterns", "Laser Pointers", "Laxatives", "Lemon Juice", "Magic Tricks", "Marble", "Markets", "Massages", "Mattresses", "Meditating", "Memes", "Mice", "Mothers", "Motivational Posters", "Movies", "Museums", "Mushrooms", "Music", "Mythology", "New Socks", "NFTs", "Night Driving", "Nightclubs", "Oreos", "Pajamas", "Pancakes", "Parachutes", "Passports", "Pastrami", "Paychecks", "PE Teachers", "Peanut Butter", "Pencil Sharpeners", "Photosynthesis", "Pigs", "Pilots", "Ping Pong Balls", "Pizza", "Pogs", "Poker", "Power", "Presidents", "Prison Breaks", "Public Speaking", "Punctuality", "Puns", "Pyramids", "Racecars", "Rain", "Reality TV", "Restaurants", "Running Water", "Runny Nose", "Samurai Art", "Sandpipers", "Sandwiches", "Sci-Fi", "Scotland", "Shoe horns", "Shouting", "Sister-in-Laws", "Sitcoms", "Snogging", "Soap", "Software Piracy", "Soldiers", "Solid furniture", "Spicy Food", "Staplers", "Stickers", "Summer Breeze", "Sunsets", "Sweat", "Swimming Pools", "Tax Evasion", "Teachers", "Tequila", "The Mafia", "The Moon", "The Void", "Thesaurus", "Tipping", "Toothbrushes", "Toy Phones", "Train Sets", "Tree Sap", "TSA Agents", "Tuna", "Underwear", "Venus", "Vigilantes", "Warmth", "Watches", "Wetness", "White wine", "Zoos"];

data.partners = {
    "Lazy Lions": ["Superfan", "Confident", "Zookeeper", "Mice", "Homeopathy"],
    "Cryptodads": ["Superfan", "Appreciative", "Assistant Coach", "Public Bathrooms", "Shoe horns"],
    "Knights of Degen": ["Player", "Innovative", "Hardcore", "Milk", "Craft Beer"],
    "SoRare": ["SuperFan", "Wise", "Analyst", "Protein Powder", "Dreams"],
    "8 Bit Sports": ["Player", "Innovative", "Die-hard", "The '80s", "NFTs"],
    "Footium": ["Manager", "Idealistic", "Full Kit Wanker", "Improv Comedy", "Boardgames"],
    "Fives": ["Manager", "Sage", "Specialist", "Tennis Elbow", "Mythical Creatures"],
    "NFTeams": ["Player", "Humorous", "Assistant Coach", "Theme Parks", "Laughing Gas"],
    "Aifa": ["Player", "Wise", "Specialist", "Sporks", "Sci-Fi"],
    "Metasoccer": ["Manager", "Idealistic", "Die-hard", "Protein Powder", "Exobiology"],
    "NFT FC": ["Player", "Idealistic", "Hardcore", "Slippers", "Hair Bands"],
    "Krause House": ["Manager", "Confident", "Ball handler", "Marching Bands", "Motivational Posters"],
    "League DAO": ["Player", "Focused", "Assistant Coach", "Exotic Dancers", "Fungible Tokens"],
    "Ballerz": ["Manager", "Humorous", "Analyst", "Moustaches", "Cheerleaders"],
    "All Star Freaks": ["Player", "Passionate", "Hardcore", "Body Spray", "Laughing Gas"],
    "Big Head Soccer Club": ["Player", "Passionate", "Specialist", "PE Teachers", "Buffets"],
    "NFTUT": ["Manager", "Confident", "Physio", "Nightclubs", "Arcades"],
    "Rookies": ["Manager", "Passionate", "Ball handler", "Toxoplasmosis", "Bad Speling"]
}

module.exports = data;
